version: "3"

services:

  consul:
    image: consul:latest
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"

  git2consul:
    image: cimpress/git2consul
    restart: always
    depends_on:
      - consul
    volumes:
      - ./config/git2consul:/config
    command: --endpoint consul --config-file /config/git2consul.json

  # Use storage type Cassandra. To use other storage like  ElasticSearch and MySQL check the examples in
  # https://github.com/openzipkin/zipkin/tree/master/docker/examples
  zipkin-storage:
    image: openzipkin/zipkin-cassandra
    container_name: cassandra
    ports:
      - 9042:9042

  zipkin-server:
    image: openzipkin/zipkin
    depends_on:
      - zipkin-storage
    environment:
      - STORAGE_TYPE=cassandra3
      # When using the test docker image, or have schema pre-installed, you don't need to re-install it
      - CASSANDRA_ENSURE_SCHEMA=false
      # When overriding this value, note the minimum supported version is 3.9
      # If you you cannot run 3.9+, but can run 2.2+, set STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=cassandra
    ports:
      - 9411:9411

  hello-service:
    image: bookstore/hello-service:v0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT: hello-service
        PORT: 8010
        MAIN_CLASS: com.meresti.bookstore.helloservice.HelloServiceApplication
    depends_on:
      - consul
      - zipkin-server
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      ZIPKIN_SERVER_URL: http://zipkin-server:9411/
      DEBUG_PORT: 2002
    ports:
      - "8010:8010"
      - "2002:2002"

  #  auth-service:
  #    image: bookstore/auth-service:v0.1
  #    build:
  #      context: ..
  #      dockerfile: docker/Dockerfile
  #      args:
  #        PROJECT: auth-service
  #        PORT: 7878
  #        MAIN_CLASS: com.meresti.bookstore.authservice.AuthServiceApplication
  #    depends_on:
  #      - config-server
  #      - eureka-service
  #    environment:
  #      CONFIG_SERVER_URL: http://config-server:9999
  #      EUREKA_SERVICE_URL: http://eureka-service:8761/eureka/
  #    ports:
  #      - "7878:7878"

  book-service:
    image: bookstore/book-service:v0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT: book-service
        PORT: 8000
        MAIN_CLASS: com.meresti.bookstore.bookservice.BookServiceApplication
    depends_on:
      - consul
      - zipkin-server
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      ZIPKIN_SERVER_URL: http://zipkin-server:9411/
      DEBUG_PORT: 4004
    ports:
      - "8020:8000"
      - "4004:4004"

  bookstore-client:
    image: bookstore/bookstore-client:v0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT: bookstore-client
        PORT: 8080
        MAIN_CLASS: com.meresti.bookstoreclient.BookstoreClientApplication
    depends_on:
      - consul
      - zipkin-server
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      ZIPKIN_SERVER_URL: http://zipkin-server:9411/
      DEBUG_PORT: 5005
    ports:
      - "8080:8080"
      - "5005:5005"
