version: "3"

networks:
  bookstore:

volumes:
  elasticsearch_data: {}
  filebeat_data: {}
  prometheus_data: {}
  grafana_data: {}

services:
  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "9080:9080"
    networks:
      - bookstore
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    command:
      - start-dev
      - --http-port=9080
      - --import-realm
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import:ro

  consul:
    image: consul:latest
    command: "agent -dev -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"
    networks:
      - bookstore

  git2consul:
    image: cimpress/git2consul
    restart: always
    depends_on:
      - consul
    volumes:
      - ./config/git2consul:/config:ro
    command: --endpoint consul --config-file /config/git2consul.json
    networks:
      - bookstore

  # Use storage type Cassandra. To use other storage like  ElasticSearch and MySQL check the examples in
  # https://github.com/openzipkin/zipkin/tree/master/docker/examples
  zipkin-storage:
    image: openzipkin/zipkin-cassandra
    ports:
      - "9042:9042"
    networks:
      - bookstore

  zipkin-server:
    image: openzipkin/zipkin:2.20.0         # the latest version (2.21.0) shows a blank page when accessing the UI
    depends_on:
      - zipkin-storage
    environment:
      - STORAGE_TYPE=cassandra3
      # When using the test docker image, or have schema pre-installed, you don't need to re-install it
      - CASSANDRA_ENSURE_SCHEMA=false
      # When overriding this value, note the minimum supported version is 3.9
      # If you cannot run 3.9+, but can run 2.2+, set STORAGE_TYPE=cassandra
      - CASSANDRA_CONTACT_POINTS=zipkin-storage
    ports:
      - "9411:9411"
    networks:
      - bookstore

  prometheus:
    image: prom/prometheus
    volumes:
      - prometheus_data:/prometheus
      - ./config/prometheus:/etc/prometheus:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    networks:
      - bookstore

  grafana:
    image: grafana/grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/grafana/provisioning/:/etc/grafana/provisioning/:ro
    env_file:
      - ./config/grafana/grafana.env
    ports:
      - "3000:3000"
    networks:
      - bookstore

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.4.3
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data:rw
    environment:
      - "discovery.type=single-node"
      - "xpack.security.enabled=false"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    networks:
      - bookstore

  logstash:
    image: docker.elastic.co/logstash/logstash:8.4.3
    depends_on:
      - elasticsearch
    volumes:
      - ./config/logstash/pipeline/:/usr/share/logstash/pipeline/:ro
    ports:
      - "25826:25826"
      - "5044:5044"
    networks:
      - bookstore
    restart: on-failure

  kibana:
    image: docker.elastic.co/kibana/kibana:8.4.3
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - bookstore
    restart: on-failure

  filebeat:
    image: docker.elastic.co/beats/filebeat:8.4.3
    volumes:
      - ./config/filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file
      - /var/lib/docker/containers:/var/lib/docker/containers:ro                  # Docker logs
      - /var/run/docker.sock:/var/run/docker.sock:ro                              # Additional information about containers
      - filebeat_data:/usr/share/filebeat/data:rw                                 # Persistence data
    user: root                                                                    # Allow access to log files and docker.sock
    restart: on-failure
    depends_on:
      - logstash
    networks:
      - bookstore

  gateway:
    image: bookstore/gateway:v0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT: gateway
        PORT: 8080
        JAR_FILE: gateway-1.0-SNAPSHOT.jar
    depends_on:
      - consul
      - zipkin-server
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      ZIPKIN_SERVER_URL: http://zipkin-server:9411/
      DEBUG_PORT: 5080
      KEYCLOACK_SERVER_URL: http://keycloak:9080
    ports:
      - "8080:8080"
      - "5080:5080"
    networks:
      - bookstore
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  hello-service:
    image: bookstore/hello-service:v0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT: hello-service
        PORT: 8010
        JAR_FILE: hello-service-1.0-SNAPSHOT.jar
    depends_on:
      - consul
      - zipkin-server
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      ZIPKIN_SERVER_URL: http://zipkin-server:9411/
      KEYCLOACK_SERVER_URL: http://localhost:9080
      DEBUG_PORT: 5010
    ports:
      - "8010:8010"
      - "5010:5010"
    networks:
      - bookstore
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  book-service:
    image: bookstore/book-service:v0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT: book-service
        PORT: 8020
        JAR_FILE: book-service-1.0-SNAPSHOT.jar
    depends_on:
      - consul
      - zipkin-server
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      ZIPKIN_SERVER_URL: http://zipkin-server:9411/
      KEYCLOACK_SERVER_URL: http://localhost:9080
      DEBUG_PORT: 5020
    ports:
      - "8020:8020"
      - "5020:5020"
    networks:
      - bookstore
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"

  bookstore-client:
    image: bookstore/bookstore-client:v0.1
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        PROJECT: bookstore-client
        PORT: 8070
        JAR_FILE: bookstore-client-1.0-SNAPSHOT.jar
    depends_on:
      - consul
      - zipkin-server
    environment:
      CONSUL_HOST: consul
      CONSUL_PORT: 8500
      ZIPKIN_SERVER_URL: http://zipkin-server:9411/
      KEYCLOACK_SERVER_URL: http://localhost:9080
      DEBUG_PORT: 5070
    ports:
      - "8070:8070"
      - "5070:5070"
    networks:
      - bookstore
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
