version: "3"

services:

  consul-agent-1: &consul-agent
    image: consul:latest
    command: "agent -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-agent-2:
    <<: *consul-agent

  consul-agent-3:
    <<: *consul-agent

  consul-server-1: &consul-server
    <<: *consul-agent
    volumes:
      - consul-server-1-data-volume:/consul/data
    command: "agent -server -retry-join consul-server-bootstrap -client 0.0.0.0"

  consul-server-2:
    <<: *consul-server
    volumes:
      - consul-server-2-data-volume:/consul/data

  consul-server-bootstrap:
    <<: *consul-server
    volumes:
      - consul-server-bootstrap-data-volume:/consul/data
    command: "agent -server -bootstrap-expect 3 -ui -client 0.0.0.0"
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
      - "8600:8600/udp"

volumes:
  consul-server-bootstrap-data-volume:
  consul-server-1-data-volume:
  consul-server-2-data-volume:
