version: "3"

services:

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - "9080:9080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KEYCLOAK_LOGLEVEL: DEBUG
    command:
      - start-dev
      - --http-port=9080
      - --import-realm
    volumes:
      - ./config/keycloak:/opt/keycloak/data/import:ro
