spring:
  application:
    name: book-service

  config:
    import: "consul:"

  cloud:
    consul:
      host: ${CONSUL_HOST:localhost}
      port: ${CONSUL_PORT:8500}
      discovery:
        enabled: true
        fail-fast: true
      config:
        enabled: true
        fail-fast: true
        format: files
        prefix: bookstore-config
        watch:
          enabled: true
      retry:
        initial-interval: 1000
        max-attempts: 10
        max-interval: 60000
        multiplier: 1.2

logging.level:
  org.springframework.retry: debug
