spring.cloud.config.server.git:
  uri: https://github.com/meresti/bookstore-config.git
  basedir: ./config

server.port: ${APP_PORT:9999}

spring.jackson.serialization.indent_output: true

management.endpoints.web.exposure.include: '*'
